### ISSUE TITLE
Function tier EP1

### ISSUE THREAD

**Issue by didsomeonecloneme** [noplacelikecloud/Azure-TableStorageBackup#1]
Hi @noplacelikecloud 

Nice work. Really useful function for the people that use tables. Tried to deploy the function, but noticed it deploys in a Azure premium function tier EP1. My calculation shows this is a pretty expensive tier ($300 a month?).

Isn't it possible to run this in a consumption tier? I'm not familiar with Windows / PowerShell functions, but if we can run this in a consumption plan, it would be way more affordable (near $0 a month). Curious about your thoughts on this

Thanks

**Comment by noplacelikecloud** [comment]
Hi @didsomeonecloneme!

EP1 is used to provide vNet Integration for the function app (consumption-based does not support vNet-Integration)

As I understand that the EP1 is really expensive for this use case, I‘ll add a Consumption based version with backup over public endpoints

Just give me a bit time for this :)

Greetings!

**Comment by noplacelikecloud** [comment]
Hi!
Is now implemented! Hope it meets your requirements

BR

**Comment by didsomeonecloneme** [comment]
Thanks, it's up and running, looks great.
